include ../../Make_common_pre
#NUMBER_OF_CU := 1

DESIGN_NAME := matrix_mult_8x8
SRCS_HOST  +=  ../src/tb_matrix_mult_8x8.cpp 
SRCS_XOCC  :=  ../src/sdx_cppKernel_top.cpp ../src/kernel_WRAPPER.cpp ../src/matrix_mult_wrapper.cpp

include ../../Make_common_post

